### ISSUE TITLE
[bug] panic when call move_model::model::StructEnv::get_variants()

### ISSUE THREAD

**Issue by robinlzw** [movebit/aptos-move-analyzer#11]
INFO - Starting language server 'C:\Users\Administrator\.cargo\bin\aptos-move-analyzer.exe' communicating via stdio...
ERROR - project '"c:/Users\\Administrator\\.move\\https___github_com_aptos-labs_aptos-core_git_main\\aptos-move\\framework\\aptos-framework\\sources\\fungible_asset.move"' not found try load.
INFO - scan modules at "c:\\Users\\Administrator\\.move\\https___github_com_aptos-labs_aptos-core_git_main\\aptos-move\\framework\\aptos-framework"
INFO - targets_paths.len() = 137
INFO - dependents_paths.len() = 87
INFO - env.get_module_count() = 111
INFO - call inlay_hints config InlayHintsConfig { enable: true }
INFO - call movefmt config FmtConfig { enable: true, max_width: 90, indent_size: 4 }
INFO - call inlay_hints config InlayHintsConfig { enable: true }
INFO - call movefmt config FmtConfig { enable: true, max_width: 90, indent_size: 4 }
INFO - on_document_symbol_request
INFO - start handle module env name: "0x1::fungible_asset"
INFO - on_document_symbol_request
INFO - start handle module env name: "0x1::fungible_asset"
INFO - handle response[Response { id: RequestId(String("inlay_hints")), result: None, error: None }] from client
INFO - handle response[Response { id: RequestId(String("movefmt")), result: None, error: None }] from client
INFO - on_inlay_hints request = Request { id: RequestId(I32(7)), method: "textDocument/inlayHint", params: Object {"range": Object {"end": Object {"character": Number(70), "line": Number(278)}, "start": Object {"character": Number(0), "line": Number(97)}}, "textDocument": Object {"uri": String("file:///c%3A/Users/Administrator/.move/https___github_com_aptos-labs_aptos-core_git_main/aptos-move/framework/aptos-framework/sources/fungible_asset.move")}} }
INFO - on_go_to_def_request request = Request { id: RequestId(I32(8)), method: "textDocument/definition", params: Object {"position": Object {"character": Number(31), "line": Number(193)}, "textDocument": Object {"uri": String("file:///c%3A/Users/Administrator/.move/https___github_com_aptos-labs_aptos-core_git_main/aptos-move/framework/aptos-framework/sources/fungible_asset.move")}} }
INFO - process_use_decl for goto definition
INFO - process_func for goto defnition
INFO - >> process_struct for goto definition
INFO - get mouse_source = Ok("        metadata: Object<Metada")
INFO - atomic_field_source = Ok("Metadata")
thread 'main' panicked at C:\Users\Administrator\.cargo\git\checkouts\aptos-core-2500b6b3b7a9b7d9\9575cb8\third_party\move\move-model\src\model.rs:3592:14:
struct has variants
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
[Info  - 11:00:51 AM] Connection to server got closed. Server will restart.
true
[Error - 11:00:51 AM] Server process exited with code 101.
INFO - Starting language server 'C:\Users\Administrator\.cargo\bin\aptos-move-analyzer.exe' communicating via stdio...
ERROR - project '"c:/Users\\Administrator\\.move\\https___github_com_aptos-labs_aptos-core_git_main\\aptos-move\\framework\\aptos-framework\\sources\\fungible_asset.move"' not found try load.
INFO - scan modules at "c:\\Users\\Administrator\\.move\\https___github_com_aptos-labs_aptos-core_git_main\\aptos-move\\framework\\aptos-framework"
INFO - targets_paths.len() = 137
INFO - dependents_paths.len() = 87
INFO - env.get_module_count() = 111
INFO - on_document_symbol_request
INFO - start handle module env name: "0x1::fungible_asset"
INFO - on_go_to_def_request request = Request { id: RequestId(I32(2)), method: "textDocument/definition", params: Object {"position": Object {"character": Number(30), "line": Number(193)}, "textDocument": Object {"uri": String("file:///c%3A/Users/Administrator/.move/https___github_com_aptos-labs_aptos-core_git_main/aptos-move/framework/aptos-framework/sources/fungible_asset.move")}} }
INFO - process_use_decl for goto definition
INFO - process_func for goto defnition
INFO - >> process_struct for goto definition
INFO - get mouse_source = Ok("        metadata: Object<Metad")
INFO - atomic_field_source = Ok("Metadata")
thread 'main' panicked at C:\Users\Administrator\.cargo\git\checkouts\aptos-core-2500b6b3b7a9b7d9\9575cb8\third_party\move\move-model\src\model.rs:3592:14:
struct has variants
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
[Info  - 11:00:52 AM] Connection to server got closed. Server will restart.
true
[Error - 11:00:52 AM] Server process exited with code 101.

**Comment by robinlzw** [comment]
fixed at https://github.com/movebit/aptos-move-analyzer/commit/d35c128aedb25a6ebcca13c5b54b010f12459940
